import { Injectable, inject } from '@angular/core';
import { LangService } from '../lang.service';

@Injectable()
export class ExperienceTranslateService {
  private lang = inject(LangService);

  private dict: Record<string, Record<string, string>> = {
    es: {
      'experience.title': 'Experiencia',
      'experience.subtitle': 'Trayectoria Profesional',
      'experience.intro': 'Mi experiencia profesional ha estado enfocada en el desarrollo de software, automatización de procesos y análisis de datos. He participado en proyectos empresariales donde he diseñado, desarrollado e implementado soluciones tecnológicas que optimizan operaciones, mejoran la gestión de la información y generan valor para las organizaciones. Cada experiencia ha fortalecido mis habilidades técnicas, mi capacidad de adaptación y mi compromiso con la mejora continua.',
      // ---------- Tarjeta 1: Desarrollador de Soluciones de IA y Ciberseguridad (LexIA, CyberGuard, SOMA) ----------
      'experience.desarrollador_soluciones_ia_ciberseguridad_title': 'Desarrollador de Soluciones de IA y Ciberseguridad',
      'experience.desarrollador_soluciones_ia_ciberseguridad_type': 'Proyectos personales · Desarrollo independiente',
      'experience.desarrollador_soluciones_ia_ciberseguridad_date': 'Mayo 2026 – Actualidad',
      'experience.desarrollador_soluciones_ia_ciberseguridad_location': 'Bello, Antioquia, Colombia · Remoto',
      'experience.desarrollador_soluciones_ia_ciberseguridad_desc': 'Diseño y desarrollo de proyectos personales de alto nivel enfocados en inteligencia artificial aplicada y ciberseguridad, integrando arquitecturas modernas, buenas prácticas y despliegue en producción.',
      'experience.highlighted_projects': 'Proyectos destacados:',
      'experience.desarrollador_soluciones_ia_ciberseguridad_proj_5': 'SecureScan Web (Angular 20 + Node.js + Express + Prisma + SQLite): Plataforma de auditoría automatizada de seguridad web que analiza HTTPS/TLS, headers de seguridad, cookies, tecnologías e información expuesta, clasifica riesgos y genera Security Scores e informes PDF con referencias a OWASP, CWE, CVE e ISO/IEC.',
      'experience.desarrollador_soluciones_ia_ciberseguridad_proj_1': 'LexIA Colombia (Angular + Node.js + PostgreSQL): Asistente legal con IA basado en arquitectura RAG, búsqueda semántica con embeddings, citas verificables y despliegue en producción con Render',
      'experience.desarrollador_soluciones_ia_ciberseguridad_proj_2': 'CyberGuard (Angular + Node.js + Python + PostgreSQL): Plataforma integral de ciberseguridad para Windows que integra Vulnerability Scanner, IDS, SIEM, gestión de alertas e incidentes y dashboard web',
      'experience.desarrollador_soluciones_ia_ciberseguridad_proj_3': 'SOMA (Node.js + Electron + SQLite) - en desarrollo: Asistente de escritorio con IA que permite interactuar con el computador mediante lenguaje natural, administrar archivos, ejecutar aplicaciones y automatizar tareas del sistema operativo',
      'experience.desarrollador_soluciones_ia_ciberseguridad_proj_4': 'Mundo de Rescate (HTML + CSS + JavaScript): Juego educativo de programación por bloques con 4 zonas y 10 personajes por rescatar, motor de puzzles con secuencias, condicionales, bucles y laberintos. Progreso guardado en el navegador, controles táctiles y sonido generado con Web Audio API, sin librerías externas',
      'experience.responsibilities': 'Logros:',
      'experience.desarrollador_soluciones_ia_ciberseguridad_resp_1': 'Análisis, diseño e implementación de arquitecturas full stack completas',
      'experience.desarrollador_soluciones_ia_ciberseguridad_resp_2': 'Integración de IA, seguridad, bases de datos y APIs en una única plataforma',
      'experience.desarrollador_soluciones_ia_ciberseguridad_resp_3': 'Despliegue en producción y control de versiones con Git y GitHub',
      'experience.desarrollador_soluciones_ia_ciberseguridad_resp_4': 'Desarrollo de soluciones de ciberseguridad con análisis automatizado de riesgos y vulnerabilidades',
      // ---------- Tarjeta 2: Analista de Datos · Conexiones Digitales BPO ----------
      'experience.conexiones_title': 'Analista de Datos | Desarrollador Full Stack',
      'experience.conexiones_company': 'Conexiones Digitales BPO S.A.S · Jornada completa',
      'experience.conexiones_date': 'Marzo 2026 – Abril 2026 · 2 meses',
      'experience.conexiones_location': 'Medellín, Antioquia, Colombia · Presencial',
      'experience.conexiones_desc': 'Analista de datos enfocado en la optimización de operaciones en tiempo real dentro de entornos de alto volumen, combinando análisis de datos con desarrollo de soluciones tecnológicas.',
      'experience.conexiones_achievements': 'Logros clave:',
      'experience.conexiones_proj_title': 'Proyecto destacado – Sistema de monitoreo en tiempo real:',
      'experience.conexiones_proj_1': 'Desarrollo de solución full stack para monitoreo de campañas en contact center',
      'experience.conexiones_proj_2': 'Implementación de dashboard con métricas en tiempo real (volumen de llamadas, estados, efectividad)',
      'experience.conexiones_proj_3': 'Desarrollo de API REST con Node.js y Express',
      'experience.conexiones_proj_4': 'Construcción de frontend con Angular y Tailwind CSS',
      'experience.conexiones_proj_5': 'Gestión de base de datos en MySQL con Sequelize',
      'experience.conexiones_proj_6': 'Implementación de autenticación segura con JWT',
      'experience.conexiones_opt': 'Optimización de procesos operativos mediante análisis de datos en tiempo real',
      // ---------- Tarjeta 3: Desarrollador Full Stack Freelance ----------
      'experience.desarrollador_full_stack_freelance_title': 'Desarrollador Full Stack Freelance',
      'experience.desarrollador_full_stack_freelance_type': 'Proyectos personales · Desarrollo independiente',
      'experience.desarrollador_full_stack_freelance_date': 'Agosto 2025 – Marzo 2026 · 8 meses',
      'experience.desarrollador_full_stack_freelance_location': 'Bello, Antioquia, Colombia · Remoto',
      'experience.desarrollador_full_stack_freelance_desc': 'Desarrollo de proyectos tecnológicos de manera autónoma enfocados en aplicaciones web, software y videojuegos, aplicando buenas prácticas de desarrollo y arquitectura.',
      'experience.desarrollador_full_stack_freelance_proj_1': 'Portafolio Web (Angular): Aplicación SPA responsive con despliegue en Firebase',
      'experience.desarrollador_full_stack_freelance_proj_2': 'Monetary Control (Angular + C# + SQL) - en desarrollo: Aplicación para el control monetario de gastos, ganancias y pérdidas, con registro de transacciones, cálculo de balances, reportes de ingresos y egresos y seguimiento del estado financiero. Integración frontend-backend y gestión de base de datos con SQL Server',
      'experience.desarrollador_full_stack_freelance_proj_3': 'Flappy Bird (Unity + C#): Videojuego 2D con implementación de físicas, colisiones y sistema de puntuación. Build ejecutable y APK funcional',
      'experience.desarrollador_full_stack_freelance_proj_4': 'Flask Web CRUD (Python + Flask + SQLite): Aplicación full stack con autenticación de usuarios y gestión de datos, desarrollada como prueba técnica para posición Frontend. CRUD completo con base de datos SQLite, validaciones frontend/backend y empaquetado como ejecutable .exe sin dependencias',
      'experience.desarrollador_full_stack_freelance_proj_5': 'Separatas POS (Angular + Node.js + MySQL + Docker): Sistema full stack para gestión de promociones dinámicas en sistemas POS con arquitectura extensible de descuentos, validación de traslape de fechas, containerización completa con Docker y pipeline CI/CD con GitHub Actions',
      'experience.desarrollador_full_stack_freelance_proj_6': 'Contacts (Angular + Firebase): Aplicación full stack para gestión de contactos personales con Firebase Auth, CRUD en Firestore en tiempo real, diseño responsive y sincronización automática entre dispositivos',
      'experience.resp_1': 'Gestión completa del ciclo de desarrollo (análisis, desarrollo, pruebas y despliegue)',
      'experience.resp_2': 'Uso de Git y GitHub para control de versiones',
      'experience.resp_3': 'Aprendizaje continuo de nuevas tecnologías',
      // ---------- Tarjeta 4: Somex Nutrición S.A.S. · Aprendiz TIC ----------
      'experience.somex_title': 'Aprendiz TIC – Área de Proyectos',
      'experience.somex_type': 'Somex Nutrición S.A.S. · Contrato de prácticas',
      'experience.somex_date': 'Febrero 2025 – Agosto 2025 · 7 meses',
      'experience.somex_location': 'Medellín, Antioquia, Colombia · Híbrido',
      'experience.somex_desc': 'Durante mi etapa en Somex Nutrición S.A.S., participé en el desarrollo y soporte de aplicaciones internas del área de Proyectos, introduciendo nuevas tecnologías en la empresa y liderando de forma autónoma los desarrollos asignados.',
      'experience.somex_web_title': 'Desarrollo Web y Backend:',
      'experience.somex_web_1': 'Desarrollé e implementé un software de inspección de lockers con Angular 19, Node.js 22 y SQL Server.',
      'experience.somex_web_2': 'Integré autenticación JWT, gestión de roles (guarda de seguridad, colaborador, testigo y encargado) y firmas digitales con @almothafar/angular-signature-pad.',
      'experience.somex_web_3': 'Construcción de API REST en MVC, manejo de archivos con Multer y procedimientos almacenados en SQL Server.',
      'experience.somex_deploy_title': 'Despliegue y Arquitectura:',
      'experience.somex_deploy_1': 'Configuración del entorno productivo con IIS y PM2 para asegurar disponibilidad continua.',
      'experience.somex_deploy_2': 'Integración de backend, frontend e imágenes mediante rutas seguras y controladas.',
      'experience.somex_auto_title': 'Automatización con Excel y SQL:',
      'experience.somex_auto_1': 'Desarrollo de macros en VBA conectadas a SQL Server permitiendo operaciones CRUD automáticas desde hojas de cálculo.',
      'experience.somex_auto_2': 'Creación de varios procedimientos almacenados que integran datos masivos desde Excel.',
      'experience.somex_powerapps_title': 'Power Apps y Power Automate:',
      'experience.somex_powerapps_1': 'Creación de dos aplicaciones empresariales:',
      'experience.somex_powerapps_1a': 'Control de correspondencia con firmas electrónicas y notificaciones por correo.',
      'experience.somex_powerapps_1b': 'Gestión de préstamos y devoluciones de lockers con registro digital y firma del colaborador.',
      'experience.somex_powerapps_2': 'Flujos en Power Automate, incluyendo sincronización automática entre Microsoft Planner y SQL Server con reportes enviados por correo.',
      'experience.somex_impact_title': 'Impacto logrado:',
      'experience.somex_impact_1': 'Optimicé procesos internos, mejoré la trazabilidad de operaciones y reduje tiempos de gestión mediante soluciones digitales implementadas en toda la organización.',
    },
    en: {
      'experience.title': 'Experience',
      'experience.subtitle': 'Professional Journey',
      'experience.intro': 'My professional experience has been focused on software development, process automation and data analysis. I have participated in business projects where I have designed, developed and implemented technological solutions that optimize operations, improve information management and generate value for organizations. Each experience has strengthened my technical skills, my adaptability and my commitment to continuous improvement.',
      // ---------- Card 1: AI and Cybersecurity Solutions Developer (LexIA, CyberGuard, SOMA) ----------
      'experience.desarrollador_soluciones_ia_ciberseguridad_title': 'Developer of AI and Cybersecurity Solutions',
      'experience.desarrollador_soluciones_ia_ciberseguridad_type': 'Personal projects · Independent development',
      'experience.desarrollador_soluciones_ia_ciberseguridad_date': 'May 2026 – Present',
      'experience.desarrollador_soluciones_ia_ciberseguridad_location': 'Bello, Antioquia, Colombia · Remote',
      'experience.desarrollador_soluciones_ia_ciberseguridad_desc': 'Design and development of high-level personal projects focused on applied artificial intelligence and cybersecurity, integrating modern architectures, best practices and production deployment.',
      'experience.highlighted_projects': 'Highlighted projects:',
      'experience.desarrollador_soluciones_ia_ciberseguridad_proj_5': 'SecureScan Web (Angular 20 + Node.js + Express + Prisma + SQLite): Automated web security auditing platform that analyzes HTTPS/TLS, security headers, cookies, technologies, and exposed information, classifies risks, and generates Security Scores and PDF reports with OWASP, CWE, CVE, and ISO/IEC references.',
      'experience.desarrollador_soluciones_ia_ciberseguridad_proj_1': 'LexIA Colombia (Angular + Node.js + PostgreSQL): Legal assistant with AI based on RAG architecture, semantic search with embeddings, verifiable citations and production deployment on Render',
      'experience.desarrollador_soluciones_ia_ciberseguridad_proj_2': 'CyberGuard (Angular + Node.js + Python + PostgreSQL): Comprehensive cybersecurity platform for Windows integrating Vulnerability Scanner, IDS, SIEM, alert and incident management and a web dashboard',
      'experience.desarrollador_soluciones_ia_ciberseguridad_proj_3': 'SOMA (Node.js + Electron + SQLite) - in development: Desktop AI assistant that allows interacting with the computer using natural language, managing files, running applications and automating operating system tasks',
      'experience.desarrollador_soluciones_ia_ciberseguridad_proj_4': 'Rescue World (HTML + CSS + JavaScript): Educational block-based programming game with 4 zones and 10 characters to rescue, puzzle engine with sequences, conditionals, loops and mazes. Progress saved in the browser, touch controls and sound generated with the Web Audio API, no external libraries',
      'experience.responsibilities': 'Achievements:',
      'experience.desarrollador_soluciones_ia_ciberseguridad_resp_1': 'Analysis, design and implementation of complete full stack architectures',
      'experience.desarrollador_soluciones_ia_ciberseguridad_resp_2': 'Integration of AI, security, databases and APIs into a single platform',
      'experience.desarrollador_soluciones_ia_ciberseguridad_resp_3': 'Production deployment and version control with Git and GitHub',
      'experience.desarrollador_soluciones_ia_ciberseguridad_resp_4': 'Development of cybersecurity solutions with automated risk and vulnerability analysis',
      // ---------- Card 2: Data Analyst · Conexiones Digitales BPO ----------
      'experience.conexiones_title': 'Data Analyst | Full Stack Developer',
      'experience.conexiones_company': 'Conexiones Digitales BPO S.A.S · Full-time',
      'experience.conexiones_date': 'March 2026 – April 2026 · 2 months',
      'experience.conexiones_location': 'Medellín, Antioquia, Colombia · On-site',
      'experience.conexiones_desc': 'Data analyst focused on real-time operations optimization within high-volume environments, combining data analysis with technological solution development.',
      'experience.conexiones_achievements': 'Key achievements:',
      'experience.conexiones_proj_title': 'Highlighted project – Real-time monitoring system:',
      'experience.conexiones_proj_1': 'Full stack solution development for contact center campaign monitoring',
      'experience.conexiones_proj_2': 'Dashboard implementation with real-time metrics (call volume, status, effectiveness)',
      'experience.conexiones_proj_3': 'REST API development with Node.js and Express',
      'experience.conexiones_proj_4': 'Frontend construction with Angular and Tailwind CSS',
      'experience.conexiones_proj_5': 'MySQL database management with Sequelize',
      'experience.conexiones_proj_6': 'Secure authentication implementation with JWT',
      'experience.conexiones_opt': 'Operations process optimization through real-time data analysis',
      // ---------- Card 3: Full Stack Freelance Developer ----------
      'experience.desarrollador_full_stack_freelance_title': 'Full Stack Freelance Developer',
      'experience.desarrollador_full_stack_freelance_type': 'Personal projects · Independent development',
      'experience.desarrollador_full_stack_freelance_date': 'August 2025 – March 2026 · 8 months',
      'experience.desarrollador_full_stack_freelance_location': 'Bello, Antioquia, Colombia · Remote',
      'experience.desarrollador_full_stack_freelance_desc': 'Independent development of technological projects focused on web applications, software and video games, applying good development and architecture practices.',
      'experience.desarrollador_full_stack_freelance_proj_1': 'Web Portfolio (Angular): Responsive SPA application deployed on Firebase',
      'experience.desarrollador_full_stack_freelance_proj_2': 'Monetary Control (Angular + C# + SQL) - in development: Application for monetary control of expenses, gains and losses, with transaction recording, balance calculation, income and expense reports and financial status tracking. Frontend-backend integration and SQL Server database management',
      'experience.desarrollador_full_stack_freelance_proj_3': 'Flappy Bird (Unity + C#): 2D video game with physics, collisions and scoring system implementation. Executable build and functional APK',
      'experience.desarrollador_full_stack_freelance_proj_4': 'Flask Web CRUD (Python + Flask + SQLite): Full stack application with user authentication and data management, developed as a technical test for a Frontend position. Complete CRUD with SQLite database, frontend/backend validations and packaging as a dependency-free .exe executable',
      'experience.desarrollador_full_stack_freelance_proj_5': 'Separatas POS (Angular + Node.js + MySQL + Docker): Full stack system for dynamic promotion management in POS systems with extensible discount architecture, date overlap validation, full Docker containerization and CI/CD pipeline with GitHub Actions',
      'experience.desarrollador_full_stack_freelance_proj_6': 'Contacts (Angular + Firebase): Full stack application for personal contact management with Firebase Auth, real-time CRUD on Firestore, responsive design and automatic synchronization across devices',
      'experience.resp_1': 'Complete development cycle management (analysis, development, testing and deployment)',
      'experience.resp_2': 'Use of Git and GitHub for version control',
      'experience.resp_3': 'Continuous learning of new technologies',
      // ---------- Card 4: Somex Nutrición S.A.S. · ICT Apprentice ----------
      'experience.somex_title': 'ICT Apprentice – Projects Area',
      'experience.somex_type': 'Somex Nutrición S.A.S. · Internship Contract',
      'experience.somex_date': 'February 2025 – August 2025 · 7 months',
      'experience.somex_location': 'Medellín, Antioquia, Colombia · Hybrid',
      'experience.somex_desc': 'During my time at Somex Nutrición S.A.S., I participated in the development and support of internal applications for the Projects area, introducing new technologies in the company and autonomously leading the assigned developments.',
      'experience.somex_web_title': 'Web Development and Backend:',
      'experience.somex_web_1': 'Developed and implemented a locker inspection software with Angular 19, Node.js 22 and SQL Server.',
      'experience.somex_web_2': 'Integrated JWT authentication, role management (security guard, collaborator, witness and supervisor) and digital signatures with @almothafar/angular-signature-pad.',
      'experience.somex_web_3': 'REST API construction in MVC, file handling with Multer and stored procedures in SQL Server.',
      'experience.somex_deploy_title': 'Deployment and Architecture:',
      'experience.somex_deploy_1': 'Production environment configuration with IIS and PM2 to ensure continuous availability.',
      'experience.somex_deploy_2': 'Integration of backend, frontend and images through secure and controlled routes.',
      'experience.somex_auto_title': 'Excel and SQL Automation:',
      'experience.somex_auto_1': 'VBA macro development connected to SQL Server enabling automatic CRUD operations from spreadsheets.',
      'experience.somex_auto_2': 'Creation of multiple stored procedures that integrate bulk data from Excel.',
      'experience.somex_powerapps_title': 'Power Apps and Power Automate:',
      'experience.somex_powerapps_1': 'Creation of two enterprise applications:',
      'experience.somex_powerapps_1a': 'Correspondence control with electronic signatures and email notifications.',
      'experience.somex_powerapps_1b': 'Locker loan and return management with digital record and collaborator signature.',
      'experience.somex_powerapps_2': 'Power Automate flows, including automatic synchronization between Microsoft Planner and SQL Server with emailed reports.',
      'experience.somex_impact_title': 'Achieved impact:',
      'experience.somex_impact_1': 'Optimized internal processes, improved operations traceability and reduced management times through digital solutions implemented across the organization.',
    },
  };

  t(key: string): string {
    return this.dict[this.lang.currentLang()]?.[key] ?? key;
  }
}
