import { Injectable, inject } from '@angular/core';
import { LangService } from '../lang.service';

@Injectable()
export class ExperienceTranslateService {
  private lang = inject(LangService);

  private dict: Record<string, Record<string, string>> = {
    es: {
      'experience.title': 'Experiencia',
      'experience.subtitle': 'Trayectoria Profesional',
      'experience.intro': 'Mi experiencia profesional ha estado enfocada en el desarrollo de software, automatización de procesos y análisis de datos. He participado en proyectos empresariales donde he diseñado, desarrollado e implementado soluciones tecnológicas que optimizan operaciones, mejoran la gestión de la información y generan valor para las organizaciones. Cada experiencia ha fortalecido mis habilidades técnicas, mi capacidad de adaptación y mi compromiso con la mejora continua.',
      'experience.conexiones_title': 'Analista de Datos | Desarrollador Full Stack',
      'experience.conexiones_company': 'Conexiones Digitales BPO S.A.S · Jornada completa',
      'experience.conexiones_date': 'Marzo 2026 – Abril 2026 · 2 meses',
      'experience.conexiones_location': 'Medellín, Antioquia, Colombia · Presencial',
      'experience.conexiones_desc': 'Analista de datos enfocado en la optimización de operaciones en tiempo real dentro de entornos de alto volumen, combinando análisis de datos con desarrollo de soluciones tecnológicas.',
      'experience.conexiones_achievements': 'Logros clave:',
      'experience.conexiones_proj_title': 'Proyecto destacado – Sistema de monitoreo en tiempo real:',
      'experience.conexiones_proj_1': 'Desarrollo de solución full stack para monitoreo de campañas en contact center',
      'experience.conexiones_proj_2': 'Implementación de dashboard con métricas en tiempo real (volumen de llamadas, estados, efectividad)',
      'experience.conexiones_proj_3': 'Desarrollo de API REST con Node.js y Express',
      'experience.conexiones_proj_4': 'Construcción de frontend con Angular y Tailwind CSS',
      'experience.conexiones_proj_5': 'Gestión de base de datos en MySQL con Sequelize',
      'experience.conexiones_proj_6': 'Implementación de autenticación segura con JWT',
      'experience.conexiones_opt': 'Optimización de procesos operativos mediante análisis de datos en tiempo real',
      'experience.freelance_title': 'Desarrollador Full Stack Freelance',
      'experience.freelance_type': 'Freelance',
      'experience.freelance_date': 'Agosto 2025 – Marzo 2026 · 8 meses',
      'experience.freelance_location': 'Bello, Antioquia, Colombia · Remoto',
      'experience.freelance_desc': 'Desarrollo de proyectos tecnológicos de manera autónoma enfocados en aplicaciones web, software y videojuegos, aplicando buenas prácticas de desarrollo y arquitectura.',
      'experience.highlighted_projects': 'Proyectos destacados:',
      'experience.freelance_proj_1': 'Portafolio Web (Angular): Aplicación SPA responsive con despliegue en Firebase',
      'experience.freelance_proj_2': 'Monetary Control (Angular + C# + SQL): Sistema en desarrollo con integración frontend-backend y gestión de base de datos',
      'experience.freelance_proj_3': 'Videojuego 2D (Unity + C#): Implementación de físicas, colisiones y sistema de puntuación. Build ejecutable y APK funcional',
      'experience.responsibilities': 'Logros:',
      'experience.resp_1': 'Gestión completa del ciclo de desarrollo (análisis, desarrollo, pruebas y despliegue)',
      'experience.resp_2': 'Uso de Git y GitHub para control de versiones',
      'experience.resp_3': 'Aprendizaje continuo de nuevas tecnologías',
      'experience.somex_title': 'Somex Nutrición S.A.S.',
      'experience.somex_type': 'Aprendiz TIC – Área de Proyectos · Contrato de prácticas',
      'experience.somex_date': 'Febrero 2025 – Agosto 2025 · 7 meses',
      'experience.somex_location': 'Medellín, Antioquia, Colombia · Híbrido',
      'experience.somex_desc': 'Durante mi etapa en Somex Nutrición S.A.S., participé en el desarrollo y soporte de aplicaciones internas del área de Proyectos, introduciendo nuevas tecnologías en la empresa y liderando de forma autónoma los desarrollos asignados.',
      'experience.somex_web_title': 'Desarrollo Web y Backend:',
      'experience.somex_web_1': 'Desarrollé e implementé un software de inspección de lockers con Angular 19, Node.js 22 y SQL Server.',
      'experience.somex_web_2': 'Integré autenticación JWT, gestión de roles (guarda de seguridad, colaborador, testigo y encargado) y firmas digitales con @almothafar/angular-signature-pad.',
      'experience.somex_web_3': 'Construcción de API REST en MVC, manejo de archivos con Multer y procedimientos almacenados en SQL Server.',
      'experience.somex_deploy_title': 'Despliegue y Arquitectura:',
      'experience.somex_deploy_1': 'Configuración del entorno productivo con IIS y PM2 para asegurar disponibilidad continua.',
      'experience.somex_deploy_2': 'Integración de backend, frontend e imágenes mediante rutas seguras y controladas.',
      'experience.somex_auto_title': 'Automatización con Excel y SQL:',
      'experience.somex_auto_1': 'Desarrollo de macros en VBA conectadas a SQL Server permitiendo operaciones CRUD automáticas desde hojas de cálculo.',
      'experience.somex_auto_2': 'Creación de varios procedimientos almacenados que integran datos masivos desde Excel.',
      'experience.somex_powerapps_title': 'Power Apps y Power Automate:',
      'experience.somex_powerapps_1': 'Creación de dos aplicaciones empresariales:',
      'experience.somex_powerapps_1a': 'Control de correspondencia con firmas electrónicas y notificaciones por correo.',
      'experience.somex_powerapps_1b': 'Gestión de préstamos y devoluciones de lockers con registro digital y firma del colaborador.',
      'experience.somex_powerapps_2': 'Flujos en Power Automate, incluyendo sincronización automática entre Microsoft Planner y SQL Server con reportes enviados por correo.',
      'experience.somex_impact_title': 'Impacto logrado:',
      'experience.somex_impact_1': 'Optimicé procesos internos, mejoré la trazabilidad de operaciones y reduje tiempos de gestión mediante soluciones digitales implementadas en toda la organización.',
    },
    en: {
      'experience.title': 'Experience',
      'experience.subtitle': 'Professional Journey',
      'experience.intro': 'My professional experience has been focused on software development, process automation and data analysis. I have participated in business projects where I have designed, developed and implemented technological solutions that optimize operations, improve information management and generate value for organizations. Each experience has strengthened my technical skills, my adaptability and my commitment to continuous improvement.',
      'experience.conexiones_title': 'Data Analyst | Full Stack Developer',
      'experience.conexiones_company': 'Conexiones Digitales BPO S.A.S · Full-time',
      'experience.conexiones_date': 'March 2026 – April 2026 · 2 months',
      'experience.conexiones_location': 'Medellín, Antioquia, Colombia · On-site',
      'experience.conexiones_desc': 'Data analyst focused on real-time operations optimization within high-volume environments, combining data analysis with technological solution development.',
      'experience.conexiones_achievements': 'Key achievements:',
      'experience.conexiones_proj_title': 'Highlighted project – Real-time monitoring system:',
      'experience.conexiones_proj_1': 'Full stack solution development for contact center campaign monitoring',
      'experience.conexiones_proj_2': 'Dashboard implementation with real-time metrics (call volume, status, effectiveness)',
      'experience.conexiones_proj_3': 'REST API development with Node.js and Express',
      'experience.conexiones_proj_4': 'Frontend construction with Angular and Tailwind CSS',
      'experience.conexiones_proj_5': 'MySQL database management with Sequelize',
      'experience.conexiones_proj_6': 'Secure authentication implementation with JWT',
      'experience.conexiones_opt': 'Operations process optimization through real-time data analysis',
      'experience.freelance_title': 'Full Stack Freelance Developer',
      'experience.freelance_type': 'Freelance',
      'experience.freelance_date': 'August 2025 – March 2026 · 8 months',
      'experience.freelance_location': 'Bello, Antioquia, Colombia · Remote',
      'experience.freelance_desc': 'Independent development of technological projects focused on web applications, software and video games, applying good development and architecture practices.',
      'experience.highlighted_projects': 'Highlighted projects:',
      'experience.freelance_proj_1': 'Web Portfolio (Angular): Responsive SPA application deployed on Firebase',
      'experience.freelance_proj_2': 'Monetary Control (Angular + C# + SQL): System in development with frontend-backend integration and database management',
      'experience.freelance_proj_3': '2D Video Game (Unity + C#): Physics, collisions and scoring system implementation. Executable build and functional APK',
      'experience.responsibilities': 'Achievements:',
      'experience.resp_1': 'Complete development cycle management (analysis, development, testing and deployment)',
      'experience.resp_2': 'Use of Git and GitHub for version control',
      'experience.resp_3': 'Continuous learning of new technologies',
      'experience.somex_title': 'Somex Nutrición S.A.S.',
      'experience.somex_type': 'ICT Apprentice – Projects Area · Internship Contract',
      'experience.somex_date': 'February 2025 – August 2025 · 7 months',
      'experience.somex_location': 'Medellín, Antioquia, Colombia · Hybrid',
      'experience.somex_desc': 'During my time at Somex Nutrición S.A.S., I participated in the development and support of internal applications for the Projects area, introducing new technologies in the company and autonomously leading the assigned developments.',
      'experience.somex_web_title': 'Web Development and Backend:',
      'experience.somex_web_1': 'Developed and implemented a locker inspection software with Angular 19, Node.js 22 and SQL Server.',
      'experience.somex_web_2': 'Integrated JWT authentication, role management (security guard, collaborator, witness and supervisor) and digital signatures with @almothafar/angular-signature-pad.',
      'experience.somex_web_3': 'REST API construction in MVC, file handling with Multer and stored procedures in SQL Server.',
      'experience.somex_deploy_title': 'Deployment and Architecture:',
      'experience.somex_deploy_1': 'Production environment configuration with IIS and PM2 to ensure continuous availability.',
      'experience.somex_deploy_2': 'Integration of backend, frontend and images through secure and controlled routes.',
      'experience.somex_auto_title': 'Excel and SQL Automation:',
      'experience.somex_auto_1': 'VBA macro development connected to SQL Server enabling automatic CRUD operations from spreadsheets.',
      'experience.somex_auto_2': 'Creation of multiple stored procedures that integrate bulk data from Excel.',
      'experience.somex_powerapps_title': 'Power Apps and Power Automate:',
      'experience.somex_powerapps_1': 'Creation of two enterprise applications:',
      'experience.somex_powerapps_1a': 'Correspondence control with electronic signatures and email notifications.',
      'experience.somex_powerapps_1b': 'Locker loan and return management with digital record and collaborator signature.',
      'experience.somex_powerapps_2': 'Power Automate flows, including automatic synchronization between Microsoft Planner and SQL Server with emailed reports.',
      'experience.somex_impact_title': 'Achieved impact:',
      'experience.somex_impact_1': 'Optimized internal processes, improved operations traceability and reduced management times through digital solutions implemented across the organization.',
    },
  };

  t(key: string): string {
    return this.dict[this.lang.currentLang()]?.[key] ?? key;
  }
}
