import { Injectable, inject } from '@angular/core';
import { LangService } from '../lang.service';

@Injectable()
export class SkillsTranslateService {
  private lang = inject(LangService);

  private dict: Record<string, Record<string, string>> = {
    es: {
      'skills.title': 'Habilidades',
      'skills.subtitle': 'Técnicas y Profesionales',
      'skills.intro': 'Mi experiencia se centra en el desarrollo de aplicaciones web, integración de sistemas, gestión de bases de datos y automatización de procesos. He participado en proyectos Full Stack donde he intervenido en el análisis, diseño, desarrollo e implementación de soluciones tecnológicas, fortaleciendo competencias tanto en frontend como en backend y manteniendo un compromiso constante con el aprendizaje de nuevas tecnologías.',
      'skills.cat_frontend': 'Frontend',
      'skills.cat_backend': 'Backend',
      'skills.cat_fullstack': 'Desarrollo Full Stack',
      'skills.cat_databases': 'Bases de Datos',
      'skills.cat_automation': 'Automatización',
      'skills.cat_deployment': 'Despliegue y Producción',
      'skills.cat_tools': 'Herramientas',
      'skills.cat_languages': 'Idiomas',
      'skills.cat_learning': 'Actualmente Aprendiendo',
      'skills.responsive': 'Diseño Responsive',
      'skills.rest_api': 'Consumo de APIs REST',
      'skills.reactive_forms': 'Formularios Reactivos',
      'skills.reusable_comp': 'Componentes reutilizables',
      'skills.role_permissions': 'Gestión de roles y permisos',
      'skills.cors_config': 'Configuración CORS',
      'skills.env_vars': 'Variables de entorno',
      'skills.file_upload': 'Subida y gestión de archivos',
      'skills.mvc_arch': 'Arquitectura MVC',
      'skills.layered_arch': 'Arquitectura por capas',
      'skills.fe_be_integration': 'Integración Frontend - Backend',
      'skills.enterprise_crud': 'CRUD Empresarial',
      'skills.enterprise_dev': 'Desarrollo de sistemas empresariales',
      'skills.realtime_dash': 'Dashboards en tiempo real',
      'skills.auth_authorization': 'Autenticación y autorización',
      'skills.component_dev': 'Desarrollo orientado a componentes',
      'skills.restful_design': 'Diseño de APIs RESTful',
      'skills.problem_solving': 'Resolución de problemas',
      'skills.stored_procedures': 'Procedimientos almacenados',
      'skills.temp_tables': 'Tablas temporales',
      'skills.advanced_sql': 'Consultas SQL avanzadas',
      'skills.relational_db': 'Diseño de bases de datos relacionales',
      'skills.sql_integration': 'Integración SQL Server + Aplicaciones',
      'skills.sql_optimization': 'Optimización de consultas SQL',
      'skills.db_modeling': 'Modelado de bases de datos',
      'skills.process_automation': 'Automatización de procesos',
      'skills.excel_sql_integration': 'Integración Excel + SQL Server',
      'skills.digitization': 'Digitalización de procesos empresariales',
      'skills.spa_config': 'Configuración SPA',
      'skills.route_cors': 'Manejo de rutas y CORS',
      'skills.prod_environments': 'Entornos productivos',
      'skills.fullstack_deploy': 'Despliegue Full Stack',
      'skills.server_config': 'Configuración de servidores',
      'skills.version_control': 'Control de versiones',
      'skills.repo_management': 'Gestión de repositorios',
      'skills.spanish': 'Español (Nativo)',
      'skills.english': 'Inglés (En formación)',
      'skills.microservices': 'Microservicios',
      'skills.scalable_arch': 'Arquitecturas escalables',
    },
    en: {
      'skills.title': 'Skills',
      'skills.subtitle': 'Technical and Professional',
      'skills.intro': 'My experience focuses on web application development, systems integration, database management and process automation. I have participated in Full Stack projects where I have been involved in the analysis, design, development and implementation of technological solutions, strengthening skills in both frontend and backend while maintaining a constant commitment to learning new technologies.',
      'skills.cat_frontend': 'Frontend',
      'skills.cat_backend': 'Backend',
      'skills.cat_fullstack': 'Full Stack Development',
      'skills.cat_databases': 'Databases',
      'skills.cat_automation': 'Automation',
      'skills.cat_deployment': 'Deployment and Production',
      'skills.cat_tools': 'Tools',
      'skills.cat_languages': 'Languages',
      'skills.cat_learning': 'Currently Learning',
      'skills.responsive': 'Responsive Design',
      'skills.rest_api': 'REST API Consumption',
      'skills.reactive_forms': 'Reactive Forms',
      'skills.reusable_comp': 'Reusable Components',
      'skills.role_permissions': 'Role and Permission Management',
      'skills.cors_config': 'CORS Configuration',
      'skills.env_vars': 'Environment Variables',
      'skills.file_upload': 'File Upload and Management',
      'skills.mvc_arch': 'MVC Architecture',
      'skills.layered_arch': 'Layered Architecture',
      'skills.fe_be_integration': 'Frontend-Backend Integration',
      'skills.enterprise_crud': 'Enterprise CRUD',
      'skills.enterprise_dev': 'Enterprise Systems Development',
      'skills.realtime_dash': 'Real-time Dashboards',
      'skills.auth_authorization': 'Authentication and Authorization',
      'skills.component_dev': 'Component-Oriented Development',
      'skills.restful_design': 'RESTful API Design',
      'skills.problem_solving': 'Problem Solving',
      'skills.stored_procedures': 'Stored Procedures',
      'skills.temp_tables': 'Temporary Tables',
      'skills.advanced_sql': 'Advanced SQL Queries',
      'skills.relational_db': 'Relational Database Design',
      'skills.sql_integration': 'SQL Server + Applications Integration',
      'skills.sql_optimization': 'SQL Query Optimization',
      'skills.db_modeling': 'Database Modeling',
      'skills.process_automation': 'Process Automation',
      'skills.excel_sql_integration': 'Excel + SQL Server Integration',
      'skills.digitization': 'Business Process Digitization',
      'skills.spa_config': 'SPA Configuration',
      'skills.route_cors': 'Route and CORS Handling',
      'skills.prod_environments': 'Production Environments',
      'skills.fullstack_deploy': 'Full Stack Deployment',
      'skills.server_config': 'Server Configuration',
      'skills.version_control': 'Version Control',
      'skills.repo_management': 'Repository Management',
      'skills.spanish': 'Spanish (Native)',
      'skills.english': 'English (Learning)',
      'skills.microservices': 'Microservices',
      'skills.scalable_arch': 'Scalable Architectures',
    },
  };

  t(key: string): string {
    return this.dict[this.lang.currentLang()]?.[key] ?? key;
  }
}
