import { Injectable, inject } from '@angular/core';
import { LangService } from '../lang.service';

@Injectable()
export class TrainingTranslateService {
  private lang = inject(LangService);

  private dict: Record<string, Record<string, string>> = {
    es: {
      'training.title': 'Formación',
      'training.subtitle': 'Académica y Complementaria',
      'training.intro': 'Mi formación académica ha sido fundamental para fortalecer mis conocimientos y habilidades en el desarrollo de software. Cada etapa de aprendizaje ha contribuido a mi crecimiento profesional, permitiéndome adquirir las competencias necesarias para enfrentar desafíos tecnológicos y desarrollar soluciones innovadoras.',
      'training.complementary_title': 'Formación Complementaria y Certificaciones',
      'training.view_diploma': 'Ver diploma',
      'training.edu_1_title': 'Ingeniería de Software',
      'training.edu_1_institution': 'Corporación Escuela Tecnológica del Oriente',
      'training.edu_1_location': 'Bucaramanga, Santander',
      'training.edu_1_date': 'Enero 2026 - Actualidad',
      'training.edu_2_title': 'Tecnólogo en Análisis y Desarrollo de Software',
      'training.edu_2_institution': 'SENA - Centro de Tecnología de la Manufactura Avanzada',
      'training.edu_2_location': 'Medellín, Antioquia',
      'training.edu_2_date': 'Mayo 2023 - Agosto 2025',
      'training.edu_3_title': 'Técnico en Sistemas',
      'training.edu_3_institution': 'SENA - Centro Industrial y de Energías Alternativas',
      'training.edu_3_location': 'Riohacha, La Guajira',
      'training.edu_3_date': 'Enero 2021 - Diciembre 2022',
      'training.edu_4_title': 'Bachiller Académico',
      'training.edu_4_institution': 'Institución Educativa Eusebio Septimio Mari',
      'training.edu_4_location': 'Riohacha, La Guajira',
      'training.edu_4_date': 'Graduado en 2022',
      'training.comp_1_title': 'Fundamentos del Sistema de Gestión de Seguridad y Salud en el Trabajo',
      'training.comp_1_institution': 'SENA',
      'training.comp_1_location': 'Riohacha, La Guajira',
      'training.comp_1_date': 'Abril 2021',
      'training.comp_2_title': 'Comportamiento Emprendedor',
      'training.comp_2_institution': 'SENA',
      'training.comp_2_location': 'Riohacha, La Guajira',
      'training.comp_2_date': 'Septiembre 2022',
      'training.comp_3_title': 'Desarrollo Web desde Cero: HTML5, CSS3 y JavaScript',
      'training.comp_3_institution': 'Udemy',
      'training.comp_3_date': 'Noviembre 2023',
      'training.comp_4_title': 'Angular de Cero a Experto: Creación de Aplicaciones Reales',
      'training.comp_4_institution': 'Udemy',
      'training.comp_4_date': 'Abril 2024',
      'training.comp_5_title': 'English Does Work - Niveles 1 al 7',
      'training.comp_5_institution': 'SENA',
    },
    en: {
      'training.title': 'Education',
      'training.subtitle': 'Academic and Complementary',
      'training.intro': 'My academic background has been fundamental in strengthening my knowledge and skills in software development. Each learning stage has contributed to my professional growth, allowing me to acquire the necessary competencies to face technological challenges and develop innovative solutions.',
      'training.complementary_title': 'Complementary Education and Certifications',
      'training.view_diploma': 'View diploma',
      'training.edu_1_title': 'Software Engineering',
      'training.edu_1_institution': 'Corporación Escuela Tecnológica del Oriente',
      'training.edu_1_location': 'Bucaramanga, Santander',
      'training.edu_1_date': 'January 2026 - Present',
      'training.edu_2_title': 'Technology in Software Analysis and Development',
      'training.edu_2_institution': 'SENA - Centro de Tecnología de la Manufactura Avanzada',
      'training.edu_2_location': 'Medellín, Antioquia',
      'training.edu_2_date': 'May 2023 - August 2025',
      'training.edu_3_title': 'Systems Technician',
      'training.edu_3_institution': 'SENA - Centro Industrial y de Energías Alternativas',
      'training.edu_3_location': 'Riohacha, La Guajira',
      'training.edu_3_date': 'January 2021 - December 2022',
      'training.edu_4_title': 'Academic High School Diploma',
      'training.edu_4_institution': 'Institución Educativa Eusebio Septimio Mari',
      'training.edu_4_location': 'Riohacha, La Guajira',
      'training.edu_4_date': 'Graduated in 2022',
      'training.comp_1_title': 'Fundamentals of Occupational Health and Safety Management System',
      'training.comp_1_institution': 'SENA',
      'training.comp_1_location': 'Riohacha, La Guajira',
      'training.comp_1_date': 'April 2021',
      'training.comp_2_title': 'Entrepreneurial Behavior',
      'training.comp_2_institution': 'SENA',
      'training.comp_2_location': 'Riohacha, La Guajira',
      'training.comp_2_date': 'September 2022',
      'training.comp_3_title': 'Web Development from Scratch: HTML5, CSS3 and JavaScript',
      'training.comp_3_institution': 'Udemy',
      'training.comp_3_date': 'November 2023',
      'training.comp_4_title': 'Angular from Zero to Expert: Creating Real Applications',
      'training.comp_4_institution': 'Udemy',
      'training.comp_4_date': 'April 2024',
      'training.comp_5_title': 'English Does Work - Levels 1 to 7',
      'training.comp_5_institution': 'SENA',
    },
  };

  t(key: string): string {
    return this.dict[this.lang.currentLang()]?.[key] ?? key;
  }
}
